### ISSUE TITLE
gosh list versions on an empty config file and no deployment repo

### ISSUE THREAD

**Issue by Geoffrey0** [ndriessen/gosh#19]
Running the command with an empty config file and on a repo that contains no deployments

docker run -v $PWD:/workdir -v $PWD/config.yml:/root/.gosh/config.yml gosh list versions

Output:

panic: interface conversion: interface {} is nil, not map[string]interface {}
goroutine 1 [running]:
gosh/util.InitializeConfig()
        /__w/gosh/gosh/util/config.go:62 +0xad9
github.com/spf13/cobra.(*Command).preRun(0xff6be0)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:882 +0x49
github.com/spf13/cobra.(*Command).execute(0xff6be0, 0xc00018bac0, 0x2, 0x2, 0xff6be0, 0xc00018bac0)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:818 +0x14f
github.com/spf13/cobra.(*Command).ExecuteC(0xff6e60, 0x200000003, 0xc000000180, 0xc00011df78)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
gosh/cmd.Execute(0xffffffff, 0xc000096058)
        /__w/gosh/gosh/cmd/root.go:34 +0x2d
main.main()
        /__w/gosh/gosh/main.go:9 +0x25

**Comment by ndriessen** [comment]
Should be able to cope without a config file
only commands that actually use config should fail with a clear error message indicating this
